<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>NunuMascotSaver</AssemblyName>
    <RootNamespace>NunuMascotSaver</RootNamespace>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Form1.cs" />
    <Compile Remove="Form1.Designer.cs" />
    <Compile Remove="buildtmp\**\*.cs" />
    <Compile Remove="screensaver\NunuMascotSaver\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\\*.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Vortice.Direct2D1" Version="3.8.2" />
  </ItemGroup>

</Project>
